# Generated by Django 3.1.6 on 2021-04-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
