# Generated by Django 3.1.6 on 2021-03-30 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_number', models.CharField(blank=True, max_length=17)),
                ('customer', models.CharField(blank=True, max_length=17)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card')], default='Cash', max_length=11)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
