# Generated by Django 3.1.6 on 2021-03-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fcontact_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
