# Generated by Django 3.1.6 on 2021-04-08 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_votes_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fcontact_number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='femail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='fname',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
