# Generated by Django 3.1.6 on 2021-03-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('F', 'Farmer'), ('I', 'Instructor')], default='F', max_length=1),
        ),
    ]
