# Generated by Django 3.1.6 on 2021-03-29 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(blank=True, max_length=100)),
                ('wgender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('waddress', models.CharField(blank=True, max_length=200)),
                ('wemail', models.EmailField(default='', max_length=254)),
                ('wcontact_number', models.CharField(blank=True, max_length=17)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('wimage', models.ImageField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
