# Generated by Django 3.1.6 on 2021-03-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210329_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='employee_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
